config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get "posts/index"
  get "posts/show"
  get "posts/new"
  get "posts/create"
  get "posts/edit"
  get "posts/update"
  get "posts/destroy"

  get "home/index"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "sessions/login"
  get "sessions/logout", to: "sessions#destroy"
  get "sessions/attempt_logout"
  post "sessions/attempt_login"

  get "users/index"
  get "users/new"
  post "users/create"
  get "users/edit"
  get "users/delete"
  get 'users/confirmation/:token', to: 'users#confirm', as: 'confirmation'

  # get 'login', to: 'sessions#login', as: 'login'
  # get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts
  resources :users


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new(role: 'guest')
    # These methods (admin?, user?) are typically defined in the User model, either manually or through an enum
    if user.admin?
      # can :manage, :all
      can :manage, Post
    elsif user.user?
      can :read, Post # Users can read posts
      can :create, Post # Users can create posts
      can :update, Post, user_id: user.id # Users can update their own posts
      can :destroy, Post, user_id: user.id # Users can delete their own posts
      can :confirm, User
    else
      can :read, :all
      can :create, User
      can :confirm, User
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_create :generate_confirmation_token
    has_secure_password

    # Creates methods (admin?, user?)
    enum role: {admin: 'admin', user: 'user', guest: 'guest'}

    validates :email, presence: true, uniqueness: true

    def generate_confirmation_token
        self.confirmation_token = SecureRandom.hex(10)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def require_login
    redirect_to login_path, alert: 'Please log in' unless logged_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all
  end

  def show
    # @post is loaded by load_and_authorize_resource
  end

  def new
    # @post is loaded by load_and_authorize_resource
  end

  def create
    @post.user = current_user  # Assign the current user to the post
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    # @post is loaded by load_and_authorize_resource
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  
  end

  def login 
    
  end
  
  def attempt_login
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully'
  end

  def attempt_logout
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'

  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # Rails.logger.debug("User Params: #{user_params.inspect}")
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      flash[:notice] = 'User created successfully.'
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'User updated successfully.'
      redirect_to root_path
    else
      render :edit
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'User destroyed successfully.'
    redirect_to root_path
  end

  def confirm
    # print "## token: #{params[:token]}"
    @user = User.find_by(confirmation_token: params[:token])
    if @user && @user.confirmed_at.nil?
      @user.update(confirmed_at: Time.now, confirmation_token: nil)
      redirect_to @user, notice: "Your email has been confirmed successfully!"
    else
      redirect_to root_path, alert: "Invalid confirmation token or email already confirmed."
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="center">
  <% if logged_in? %>
    <p>Welcome, <%= current_user.email %>! Your role is: <%= current_user.role %>.</p>
    <%= link_to 'Logout', sessions_logout_path, method: :delete %>
  <% else %>
    <p>You are not logged in. 
    <%= link_to 'Login', sessions_login_path %></p>
    <%= link_to 'Sign up', users_new_path %>
  <% end %>

  <%= link_to "Post", posts_index_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Authorization App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="center">
      <%= link_to "Home", root_path%>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.submit 'Update Post' %>
  </div>
<% end %>

<%= link_to 'Back', post_path(@post) %>

app/views/posts/index.html.erb
<div class="center">
  <h1>Posts</h1>

  <% if logged_in? %>
    <%= link_to 'New Post', new_post_path %>
  <% end %>

  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= link_to post.title, post_path(post) %>
        <% if logged_in? && post.user == current_user %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<div class="center">
  <h1>New Post</h1>

  <%= form_with(model: @post, local: true) do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div>
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
    <div>
      <%= form.submit 'Create Post' %>
    </div>
  <% end %>

  <%= link_to 'Back', posts_path %>


</div>

app/views/posts/show.html.erb
<div class="center">
  <h1><%= @post.title %></h1>
  <p><%= @post.body %></p>
  <p>Posted by: <%= @post.user.email %></p>

  <%= link_to 'Back', posts_path %>
  <% if logged_in? && @post.user == current_user %>
    <%= link_to 'Edit', edit_post_path(@post) %>
    <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="center">
    <h1>Signup</h1>
    <%= form_with(model: @user, url: users_create_path, method: :post) do |f| %>
        <div>
            <%= f.label :username, "Username" %>
            <%= f.text_field :username %>
        </div>

        <div>
            <%= f.label :email, "Email" %>
            <%= f.email_field :email %>
        </div>

        <div>
            <%= f.label :password, "Password" %>
            <%= f.password_field :password %>
        </div>

        <div>
            <%= f.label :role, "Role" %>
            <%= f.select :role, {Admin: 'admin', User: 'user', Guest: 'guest'} %>
        </div>

        <div>
            <%= f.submit "Submit", disable_with: 'Submiting...' %>
        </div>
    <% end %>


</div>

app/views/users/show.html.erb
<div class="center">
    <h1><%= @user.username %></h1>
    <p>Email: <%= @user.email %></p>

</div>